### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DigiAngel** [MarkBaggett/MarkBaggett#1]
Great tool Mark...thank you.  I'm requesting a....bulk mode I guess for using freq.  Something like the below:

```
python freq.py -f list_of_domain_names.txt --measure custom.freq
```

I'm planning on generating reports using freq, and the first step is to get freq to be able test a large amount of names.  Thank you.

**Comment by MarkBaggett** [comment]
Hi,
I can do that for you.  Good idea. Let me make sure I understand the
request.   The file "list_of_domain_names.txt" is a list of domain names
that you want to measure?   Right now -f is already used to feed it a list
of domains from which you build the frequency table.

Until I add the feature you can do this from the command line like I did
below.  It tests every domain in the file test_these.txt

C:\host\Documents\PythonProjects\freq>type test_these.txt
domain1.com
lkjadsflkjadkfl.com
somethingnormal.com
0934ljs09fnbsllk.com

C:\host\Documents\PythonProjects\freq>for /f %i in (test_these.txt) do
python fr
eq.py --measure %i english_lowercase.freq

C:\host\Documents\PythonProjects\freq>python freq.py --measure domain1.com
engli
sh_lowercase.freq
8.53901551902

C:\host\Documents\PythonProjects\freq>python freq.py --measure
lkjadsflkjadkfl.c
om english_lowercase.freq
3.64414276548

C:\host\Documents\PythonProjects\freq>python freq.py --measure
somethingnormal.c
om english_lowercase.freq
11.2051541958

C:\host\Documents\PythonProjects\freq>python freq.py --measure
0934ljs09fnbsllk.
com english_lowercase.freq
3.65128336548

On Linux you could do this:

student@573:~$ for i in `cat test_these.txt`; do python freq.py --measure
$i english_lower.freq ; done
python freq.py --measure domains.txt english_lower.freq
python freq.py --measure 02934ljksfuasdflkjadf.com english_lower.freq
python freq.py --measure lkjasdfuwer198fn.com english_lower.freq
python freq.py --measure somethingnormal.com english_lower.freq

**Comment by DigiAngel** [comment]
HI Mark...thanks so much for looking at this.
I am indeed using linux and I guess I could do the "for i in" method.  My goel is to awk out the domain name from my bro-ids dns.log to a file, then parse it against freq to generate a daily report of domains that hit a certain low frequency.  I'll try the "for i in" method next week.  Thanks again..love your work.

**Comment by MarkBaggett** [comment]
DigiAngel,

Would you mind testing the attached version before I commit it?  Let me
know how this version works for you.  How would you like the output
formatted to make it most useful?

Thanks for the suggestion.

student@573:~/git/MarkBaggett/freq$ python freq.py -b ./domains.txt
english_lowercase.freq
[+] lskdjflakou13.com 4.15949306405
[+] domain1.com 8.53901551902
[+] cia.gov 2.52665938519
[+] somethingnormal.com 11.2051541958
[+] 2309ujnvcadskvalmawlked.com 6.15520682145

**Comment by DigiAngel** [comment]
Hi Mark...I was unable to find an attached version in this chain (most likely I'm not looking right), but the above output looks good.  Changes are I will sed out the [+] and sort by the second column.  Now...I have a couple more feature requests :)  Would you like me to put them here, or create new requests?  Thanks so much for the work on this Mark.

James

**Comment by MarkBaggett** [comment]
Just email me what you would like. 

Mark

**Comment by DigiAngel** [comment]
I sure will thank you.
