### ISSUE TITLE
set-kbled help

### ISSUE THREAD

**Issue by FredSRichardson** [MarkBaggett/MarkBaggett#4]
I suspect that some new version of the Clevo drivers has changed things.  I got the following error while trying to run you module.  With some help I might be able to figure out what's going on.  I take it the key is getting the Linux driver code for this?  Any pointers would be greatly appreciated!

```
PS C:\Users\frichard> SET-KBLED -LeftColor RED -CenterColor WHITE -RightColor Blue
get-wmiobject : Invalid class "CLEVO_GET"
At C:\powershell\set-kbled.ps1:45 char:14
+ ...    $clevo = get-wmiobject -query "select * from CLEVO_GET" -namespace ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

4026597120
You cannot call a method on a null-valued expression.
At C:\powershell\set-kbled.ps1:50 char:9
+         $clevo.SetKBLED( $col  )
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\powershell\set-kbled.ps1:54 char:9
+         $clevo.SetKBLED( $col  )
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\powershell\set-kbled.ps1:58 char:9
+         $clevo.SetKBLED( $col  )
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

PS C:\Users\frichard>
```

**Comment by MarkBaggett** [comment]
Hmm.  I installed all the clevo keyboard software so I am not sure exactly
where the DLL that registers the COM object came from.   I believe you need
clevomof.dll.    This sits in my \windows\syswow64 directory.   It may have
come with the HOTKEY software.

Mark

**Comment by FredSRichardson** [comment]
If I just copy the DLL over will that do it?

I was also looking at the Linux drivers.  It appears those also make WMI
calls that appear to be generic - so unless there is some secret Clevo code
in the Linux kernel the API would have to come from hadware somehow...

**Comment by MarkBaggett** [comment]
You would also have to register the dll.  regsrv32.exe would do it but if
you ware using Windows I recommend trying Installing the Hotkey drivers.
That should do it for you.

**Comment by FredSRichardson** [comment]
The HotKey drivers are from Clevo?  I notice that CCC is installed in the
HotKey directory.

The somewhat insane issue I have is that I ran into extreme overheating of
my GPU after installing CCC and I'm not sure why.  I think it might have
changed voltages on my GPU or something (fans were cranking at the time).

A kbdled app that bypassed other CCC functionality would be great.  What I
don't know is if this can be done without using all the rest of CCC... or
having CCC do things to my settings...

**Comment by MarkBaggett** [comment]
I hope you've resolved this driver issue.  I'm closing the ticket.
